// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqgkjvudjidizbpxfnln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxZ2tqdnVkamlkaXpicHhmbmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODgxNjIsImV4cCI6MjA2NzA2NDE2Mn0.5aF6DQY6djHMwDR3eEVYxZrUnqP-etP5xaP44WD98kc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});